from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import DeclarativeBase, sessionmaker

from .config import get_settings

settings = get_settings()

connect_args = {}
_database_url = settings.DATABASE_URL
# Normalize bare postgresql:// URLs (e.g. as generated by Neon) to the psycopg3
# dialect used by this project.
if _database_url.startswith("postgresql://"):
    _database_url = _database_url.replace("postgresql://", "postgresql+psycopg://", 1)
if _database_url.startswith("sqlite"):
    connect_args["check_same_thread"] = False

engine = create_engine(_database_url, connect_args=connect_args, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def _fresh_student_id(taken: set) -> str:
    """Return a random, unused 6-digit student ID."""
    import random

    while True:
        candidate = f"{random.randint(0, 999999):06d}"
        if candidate not in taken:
            return candidate


def run_migrations() -> None:
    """Idempotent, lightweight schema updates for pre-existing databases.

    create_all() only adds brand-new tables, so columns added to existing tables
    afterwards must be applied explicitly here (safe to call on every boot).
    """
    with engine.begin() as conn:
        try:
            tables = inspect(conn).get_table_names()
        except Exception:
            return
        if "live_classes" in tables:
            cols = {c["name"] for c in inspect(conn).get_columns("live_classes")}
            if "invite_key" not in cols:
                conn.execute(text("ALTER TABLE live_classes ADD COLUMN invite_key VARCHAR(16) DEFAULT ''"))

        # 6-digit student IDs for learner accounts.
        if "users" in tables:
            cols = {c["name"] for c in inspect(conn).get_columns("users")}
            if "receipt_url" not in cols:
                conn.execute(text("ALTER TABLE users ADD COLUMN receipt_url VARCHAR(512) DEFAULT ''"))
            if "student_id" not in cols:
                conn.execute(text("ALTER TABLE users ADD COLUMN student_id VARCHAR(6)"))
                conn.execute(
                    text("CREATE UNIQUE INDEX ix_users_student_id ON users (student_id) WHERE student_id IS NOT NULL")
                )
            taken = {row[0] for row in conn.execute(text("SELECT student_id FROM users WHERE student_id IS NOT NULL"))}
            missing = conn.execute(
                text("SELECT id FROM users WHERE role = 'learner' AND (student_id IS NULL OR student_id = '')")
            ).fetchall()
            for (user_id,) in missing:
                student_id = _fresh_student_id(taken)
                taken.add(student_id)
                conn.execute(
                    text("UPDATE users SET student_id = :sid WHERE id = :uid"), {"sid": student_id, "uid": user_id}
                )

        # Parent -> student links (one parent can watch many students).
        if "parent_students" not in tables:
            conn.execute(
                text(
                    """
                    CREATE TABLE parent_students (
                        id SERIAL PRIMARY KEY,
                        parent_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                        student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                        CONSTRAINT uq_parent_student UNIQUE (parent_id, student_id)
                    )
                    """
                )
            )

        # Certificates / ID cards issued to students.
        if "certificates" not in tables:
            conn.execute(
                text(
                    """
                    CREATE TABLE certificates (
                        id SERIAL PRIMARY KEY,
                        kind VARCHAR(16) NOT NULL,
                        course_title VARCHAR(255) NOT NULL DEFAULT '',
                        student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                        issued_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                    )
                    """
                )
            )