from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker

from .config import get_settings

settings = get_settings()

connect_args = {}
_database_url = settings.DATABASE_URL
# Normalize bare postgresql:// URLs (e.g. as generated by Neon) to the psycopg3
# dialect used by this project.
if _database_url.startswith("postgresql://"):
    _database_url = _database_url.replace("postgresql://", "postgresql+psycopg://", 1)
if _database_url.startswith("sqlite"):
    connect_args["check_same_thread"] = False

engine = create_engine(_database_url, connect_args=connect_args, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()