from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import DeclarativeBase, sessionmaker

from .config import get_settings

settings = get_settings()

connect_args = {}
_database_url = settings.DATABASE_URL
# Normalize bare postgresql:// URLs (e.g. as generated by Neon) to the psycopg3
# dialect used by this project.
if _database_url.startswith("postgresql://"):
    _database_url = _database_url.replace("postgresql://", "postgresql+psycopg://", 1)
if _database_url.startswith("sqlite"):
    connect_args["check_same_thread"] = False

engine = create_engine(_database_url, connect_args=connect_args, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def run_migrations() -> None:
    """Idempotent, lightweight schema updates for pre-existing databases.

    create_all() only adds brand-new tables, so columns added to existing tables
    afterwards must be applied explicitly here (safe to call on every boot).
    """
    with engine.begin() as conn:
        try:
            tables = inspect(conn).get_table_names()
        except Exception:
            return
        if "live_classes" in tables:
            cols = {c["name"] for c in inspect(conn).get_columns("live_classes")}
            if "invite_key" not in cols:
                conn.execute(text("ALTER TABLE live_classes ADD COLUMN invite_key VARCHAR(16) DEFAULT ''"))